# Use --skip-tags "rand_pass" to avoid change of user passwords
---
- name: Bootsrap 
  hosts: all,!localhost,!127.0.0.1
  connection: paramiko
  become: yes
  handlers:
  - name: restart sshd
    service: name=sshd state=restarted
  tasks:
  - include_role:
      name: cleanup_users
      tasks_from: cleanup
