---
- name: OS Information
  hosts: all,!localhost,!127.0.0.1
  connection: paramiko
  gather_facts: no
  become: no
  ignore_errors: yes
    
  tasks:
  - name: Get version information
    raw: 'echo {{ inventory_hostname }}: $HOSTNAME && cat /etc/*release* 2>/dev/null || cat /etc/*version* 2>/dev/null || echo Unknown'
    register: info
    changed_when: False

  - name: Ensure recce path exists
    local_action: file dest=~/.ansible/files/recce state=directory
    run_once: yes 

  - name: Write info to file
    local_action: "shell echo '{{ info.stdout }}' >> ~/.ansible/files/recce/hostinfo.txt"
