---
- name: Reconnaissance (Linux)
  hosts: linux,!localhost,!127.0.0.1
  connection: paramiko
  become: yes
  tasks:
    - name: Docker reconnaissance
      import_role:
        name: recon
        tasks_from: docker_only_slow
